### ISSUE TITLE
`tar` a directory from memfs

### ISSUE THREAD

**Issue by cirocosta** [src-d/go-billy#17]
Hey!

I'd like to know if any of you've ever had experience `tar`ing a memfs tree. Would that be possible using https://golang.org/pkg/archive/tar/ reading the files directly from memfs? Are there any missing abstractions?

As i see here is where it would rely on specifics of a filesystem: https://golang.org/pkg/archive/tar/#FileInfoHeader as it accepts `os.FileInfo`, thus it must have the properties properly set. Does `memfs` comply completely with `os.FileInfo`? Would i have troubles implementing something like this?

Thx!

**Comment by cirocosta** [comment]
Didn't really try yet but adapting code from `archiver`'s `tar.go` (https://github.com/mholt/archiver/blob/master/tar.go#L115):

```go
func memFsTarFile(tarWriter *tar.Writer,source string, baseDir string, path string, fs billy.Filesystem) error {
	info, err := fs.Stat(path)
	if err != nil {
		panic(err)
	}

	header, err := tar.FileInfoHeader(info, path)
	if err != nil {
		panic(err)
	}

	if baseDir != "" {
		header.Name = filepath.Join(baseDir, strings.TrimPrefix(path, source))
	}

	if info.IsDir() {
		header.Name += "/"
	}

	err = tarWriter.WriteHeader(header)
	if err != nil {
		panic(err)
	}

	if info.IsDir() {
		files, err := fs.ReadDir(source)
		if err != nil {
			panic(err)
		}

		for _, f := range files {
			if err = memFsTarFile(tarWriter, source, baseDir, filepath.Join(source, f.Name()), fs); err != nil {
				panic(err)
			}
		}

		return nil
	}

	if header.Typeflag == tar.TypeReg {
		file, err := fs.Open(path)
		if err != nil {
			panic(err)
		}
		defer file.Close()

		bytesWritten, err := io.CopyN(tarWriter, file, info.Size())
		if err != nil && err != io.EOF {
			panic(err)
		}
	}

	return nil
}
```

**Comment by smola** [comment]
@cirocosta Yes. It's definitely possible. Your code looks on the right track.

We might add methods Walk and Glob to billy to ease this kind of operations, but you can still do it without them.
