### ISSUE TITLE
Add support for creating symlinks.

### ISSUE THREAD

**Issue by jmalloc** [src-d/go-billy#28]
This would be needed facilitate src-d/go-git#358.

For the sake of simplicity and predictability, I propose adding a `Filesystem.Symlink()` method with semantics identical to [`os.Symlink()`](https://golang.org/pkg/os/#Symlink).

To implement src-d/go-git#358 it's necessary to symlink to files that do not exist (because the checkout is still in progress), which is not possible with `os.Symlink()`. That said, I think it's safer to work around this in `go-git`, perhaps with temporary files, rather than trying to implement this functionality atomically in Billy.

If this approach seems reasonable to the project maintainers, I'll make an attempt at an implementation.

/cc @smola

**Comment by smola** [comment]
@jmalloc If we add `Symlink` to the `billy.Filesystem` interface, we'd need to bump version to `v3`. So my proposal would be adding `Symlink` function to implementations in `v2`, and defer exposing it in `billy.Filesystem`.

Mimicking `os.Symlink` as much as possible is definitely the way to go. PRs are welcome ;-)

**Comment by jmalloc** [comment]
I have a question about the behaviour of the `subdir` filesystem and how best to implement `Symlink()` there. First some background; `subdir.New()` doesn't create the `subdirFs.base` sub-directory on the underlying filesystem. As best I can tell, this doesn't usually present any problem because:

- `Filesystem.Create()` creates all parent directories when the `O_CREATE` flag is set.  
- There is no `Filesystem.Mkdir()` only `MkdirAll()`, and hence no way that directory creation can fail just because `subdirFs.base` does not exist.

This presents a small problem for `Symlink()`, which always fails because the base directory is never created. In light of that, should I:

1. Create `subdirFs.base` if it does not exist. This most closely mirrors the behaviour of the standard library insofar as `Symlink()` will fail if anything deeper than `base` does not exist.
1. Create all necessary parent directories. This more closely mirrors the behaviour of `Filesystem.Create()`.

I'll proceed with option (2) for now to best maintain consistency within Billy's API. Please let me know if some other behaviour is more desirable.

Note: Just like `osfs.OS.Create()`, any directories created will remain if symlink creation fails.

As an aside, my comment about not being able to create symlinks to non-existent files with `os.Symlink()` appears to be a blatant lie ;)

**Comment by smola** [comment]
@jmalloc SubdirFs should just delegate the Symlink call to the underlying filesystem if it does implement the Symlink function, or return an error otherwise.

Then the underlying filesystem should create directories as needed.

**Comment by smola** [comment]
@jmalloc Are you working on this? Feel free to create a partial PR to get further feedback, we can also help completing it.

**Comment by jmalloc** [comment]
I am. I have implementations for the`os` and `subdir` filesystems, but I haven't yet found time to complete the memory-based implementation. I'm submit a PR with what I have so far when I get a chance.

**Comment by smola** [comment]
@jmalloc Thank you! We'll review it soon and figure out how to move it forward.
