### ISSUE TITLE
bring back tmpoverlayfs

### ISSUE THREAD

**Issue by smola** [src-d/go-billy#39]
While the new `mount` functionality is a good addition for some use cases, the older `tmpoverlayfs` provided a more consistent solution to provide temporary files complementary to a archive or network storage. Relying on `mount` for this leads to this kind of workarounds: https://github.com/src-d/go-billy-siva/pull/9

If this needs clarification, I'll post the full explanation and rationale at some point.

**Comment by alcortesm** [comment]
@ajnavarro explained some of the current functionality in a thread in slack, I'm attaching it here:
![screenshot_2017-06-28_12-32-01](https://user-images.githubusercontent.com/9169414/27633142-541a3b04-5bfe-11e7-8306-22a49b883d39.png)
![screenshot_2017-06-28_12-32-35](https://user-images.githubusercontent.com/9169414/27633147-55a942f8-5bfe-11e7-80f9-fe30b7a30ad1.png)

**Comment by mcuadros** [comment]
as discussed offline we are not taking this direction.
