### ISSUE TITLE
We are importing gopkg.in/check.v1 in files without _test suffix.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-billy#40]
`test/chroot.go`, `test/dir.go`, `test/symlink.go` and `test/fs.go` are importing this dependency. I think we should add the _test suffix to these files to avoid that.

**Comment by alcortesm** [comment]
The `test` package have little documentation ([go-billy.v3 at go-doc](http://godoc.org/gopkg.in/src-d/go-billy.v3/test)) but I guess from the only 3 lines in there that the main purpose of this package is to be imported by other billy implementations so they can tests billy functionlity easier.

If that is the case, adding a `_test.go` suffix to those files will hide their API and it will no longer be posible to import its functionality, defeating the only goal of the package enterily.

I think a much better solution would be to properly document the package and its goals.
