### ISSUE TITLE
Comparison with afero?

### ISSUE THREAD

**Issue by progrium** [src-d/go-billy#45]
I was working with go-git and saw it used this "billy.Filesystem" abstraction. I was surprised it wasn't [afero](https://github.com/spf13/afero). Is there much of a difference? I imagine I can write a simple wrapper that fixes any slight differences...

**Comment by mcuadros** [comment]
go-billy was part of the original code of go-git, at that time afero wasn't fulfillment our requirements. Nowadays functionality such as [`chroot`](https://godoc.org/gopkg.in/src-d/go-billy.v3/helper/chroot) or [`mount`](https://godoc.org/gopkg.in/src-d/go-billy.v3/helper/mount) doesn't allow us to change to afero.
