### ISSUE TITLE
New release that comes with capabilities interface

### ISSUE THREAD

**Issue by jfontan** [src-d/go-billy#60]
A new release is needed to make use of the new capabilities interface.

**Comment by gedw99** [comment]
The capabilities interface is a security layer ?

**Comment by jfontan** [comment]
It's not a security later. It's a new method used to query which features are available in a filesystem:

https://github.com/src-d/go-billy/pull/59

A new release with this feature is already done:

https://github.com/src-d/go-billy/releases/tag/v4.2.0
